### ISSUE TITLE
Add domain to dumper

### ISSUE THREAD

**Issue by TechnomageLiloi** [TechnomageLiloi/Dumper#2]
# Tasks

- [ ] Add database adapter to manager
- [ ] Add get list formed to dump
- [ ] Create version record
- [ ] Create atom record
